set nocompatible
filetype plugin on
syntax on
set nomodeline
set ruler
set ignorecase
set smartcase
set laststatus=2
set virtualedit=block
set nohidden
set nobackup
set backspace=indent,eol,start
set noswapfile
set tabstop=8
set softtabstop=2
set shiftwidth=2
set expandtab
set autoindent
set nonumber
set iskeyword+=-
set visualbell
set t_vb=
